<a href="https://colab.research.google.com/github/b-a-sabbir/Zomato-average-cost-prediction/blob/main/zomato.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [60]:
data = pd.read_csv('zomato.csv', encoding='latin-1')
data.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [61]:
data.shape

(9551, 21)

In [62]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [63]:
data['Rating color']=data['Rating color'].astype('category')
data.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [64]:
data['Rating text']=data['Rating text'].astype('category')
data.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [65]:
data['Locality Verbose'].value_counts()

Locality Verbose
Connaught Place, New Delhi                          122
Rajouri Garden, New Delhi                            99
Shahdara, New Delhi                                  87
Defence Colony, New Delhi                            86
Pitampura, New Delhi                                 85
                                                   ...
UB City, Bangalore                                    1
Vinayak City Centre Mall, Civil Lines, Allahabad      1
Tagore Town, Allahabad                                1
The Fern, Sola, Ahmedabad                             1
Akashwani, Aurangabad                                 1
Name: count, Length: 1265, dtype: int64

In [66]:
data[data['Locality Verbose']==data['Locality']]

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
9384,6113680,Restaurant Gordon Ramsay,215,London,"68 Royal Hospital Road, Chelsea, London SW3 4HP",Chelsea,Chelsea,-0.162092,51.485509,French,...,Pounds(£),No,No,No,No,4,4.7,Dark Green,Excellent,320
9386,6100054,Masala Zone,215,London,"48 Floral Street, Covent Garden, London WC2E 9DA",Covent Garden,Covent Garden,-0.123132,51.513196,"Indian, Curry",...,Pounds(£),Yes,No,No,No,2,4.1,Green,Very Good,316
9390,6102866,Hakkasan,215,London,"17 Bruton Street, Mayfair, London W1J 6QB",Mayfair,Mayfair,-0.144861,51.510342,"Chinese, Dim Sum",...,Pounds(£),Yes,No,No,No,4,4.8,Dark Green,Excellent,395
9391,6103868,Nobu,215,London,"15 Berkeley Street, Mayfair, London W1J 8DY",Mayfair,Mayfair,-0.143259,51.508811,"Japanese, Sushi",...,Pounds(£),Yes,No,No,No,4,4.4,Green,Very Good,311

In [67]:
data['Price range'].value_counts()

Price range
1    4444
2    3113
3    1408
4     586
Name: count, dtype: int64

In [68]:
data.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [69]:
data.drop(columns=['Restaurant ID','Is delivering now','Switch to order menu','Rating color', 'Rating text'],inplace=True)

In [70]:
data.columns

Index(['Restaurant Name', 'Country Code', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [71]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant Name       9551 non-null   object
 1   Country Code          9551 non-null   int64
 2   City                  9551 non-null   object
 3   Address               9551 non-null   object
 4   Locality              9551 non-null   object
 5   Locality Verbose      9551 non-null   object
 6   Longitude             9551 non-null   float64
 7   Latitude              9551 non-null   float64
 8   Cuisines              9542 non-null   object
 9   Average Cost for two  9551 non-null   int64
 10  Currency              9551 non-null   object
 11  Has Table booking     9551 non-null   object
 12  Has Online delivery   9551 non-null   object
 13  Price range           9551 non-null   int64
 14  Aggregate rating      9551 non-null   float64
 15  Votes                 9551 non-null   int64
dtypes: float64(3), int64(4), object(9)
memory usage: 1.2+ MB

In [72]:
data.corr(numeric_only=True)

,Country Code,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
Country Code,1.000000,-0.698299,0.019792,0.043225,0.243327,0.282189,0.154530
Longitude,-0.698299,1.000000,0.043207,0.045891,-0.078939,-0.116818,-0.085101
Latitude,0.019792,0.043207,1.000000,-0.111088,-0.166688,0.000516,-0.022962
Average Cost for two,0.043225,0.045891,-0.111088,1.000000,0.075083,0.051792,0.067783
Price range,0.243327,-0.078939,-0.166688,0.075083,1.000000,0.437944,0.309444
Aggregate rating,0.282189,-0.116818,0.000516,0.051792,0.437944,1.000000,0.313691
Votes,0.154530,-0.085101,-0.022962,0.067783,0.309444,0.313691,1.000000

In [73]:
data['Country Code'].value_counts()

Country Code
1      8652
216     434
215      80
30       60
189      60
214      60
148      40
208      34
14       24
162      22
94       21
166      20
184      20
191      20
37        4
Name: count, dtype: int64

In [74]:
data=data[data['Country Code']==1]

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8652 entries, 624 to 9275
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant Name       8652 non-null   object
 1   Country Code          8652 non-null   int64
 2   City                  8652 non-null   object
 3   Address               8652 non-null   object
 4   Locality              8652 non-null   object
 5   Locality Verbose      8652 non-null   object
 6   Longitude             8652 non-null   float64
 7   Latitude              8652 non-null   float64
 8   Cuisines              8652 non-null   object
 9   Average Cost for two  8652 non-null   int64
 10  Currency              8652 non-null   object
 11  Has Table booking     8652 non-null   object
 12  Has Online delivery   8652 non-null   object
 13  Price range           8652 non-null   int64
 14  Aggregate rating      8652 non-null   float64
 15  Votes                 8652 non-null   int64
dtypes: float64(3), int64(4), object(9)
memory usage: 1.1+ MB

In [76]:
data.shape

(8652, 16)

In [77]:
data['City'].value_counts()

City
New Delhi       5473
Gurgaon         1118
Noida           1080
Faridabad        251
Ghaziabad         25
Guwahati          21
Lucknow           21
Bhubaneshwar      21
Ahmedabad         21
Amritsar          21
Allahabad         20
Varanasi          20
Coimbatore        20
Chennai           20
Bhopal            20
Aurangabad        20
Bangalore         20
Agra              20
Goa               20
Kolkata           20
Jaipur            20
Kochi             20
Kanpur            20
Mangalore         20
Ludhiana          20
Indore            20
Dehradun          20
Vizag             20
Pune              20
Mumbai            20
Mysore            20
Nashik            20
Nagpur            20
Patna             20
Puducherry        20
Ranchi            20
Vadodara          20
Surat             20
Chandigarh        18
Hyderabad         18
Secunderabad       2
Mohali             1
Panchkula          1
Name: count, dtype: int64

In [78]:
data=data[data['City'].isin(['New Delhi','Gurgaon','Noida','Faridabad'])]

In [79]:
data.shape

(7922, 16)

In [80]:
data.columns

Index(['Restaurant Name', 'Country Code', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [81]:
data.drop(columns=['Country Code','Address','Locality', 'Locality Verbose','Currency','Restaurant Name', 'Longitude', 'Latitude'],inplace=True)

In [82]:
data.shape

(7922, 8)

In [83]:
data['Has Table booking'].replace({'Yes':1,'No':0},inplace=True)
data['Has Online delivery'].replace({'Yes':1,'No':0},inplace=True)

/tmp/ipython-input-171664141.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Has Table booking'].replace({'Yes':1,'No':0},inplace=True)
/tmp/ipython-input-171664141.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Has Table booking'].replace({'Yes':1,'No':0},inplace=True)
/tmp/ipython-input-171664141.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Has Online delivery'].replace({'Yes':1,'No':0},inplace=True)
/tmp/ipython-input-171664141.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Has Online delivery'].replace({'Yes':1,'No':0},inplace=True)

In [84]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7922 entries, 865 to 9112
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   City                  7922 non-null   object
 1   Cuisines              7922 non-null   object
 2   Average Cost for two  7922 non-null   int64
 3   Has Table booking     7922 non-null   int64
 4   Has Online delivery   7922 non-null   int64
 5   Price range           7922 non-null   int64
 6   Aggregate rating      7922 non-null   float64
 7   Votes                 7922 non-null   int64
dtypes: float64(1), int64(5), object(2)
memory usage: 557.0+ KB

In [85]:
data.corr(numeric_only=True)['Average Cost for two']

Average Cost for two    1.000000
Has Table booking       0.642966
Has Online delivery     0.076953
Price range             0.847985
Aggregate rating        0.328440
Votes                   0.299089
Name: Average Cost for two, dtype: float64

In [86]:
len(data['Cuisines'].value_counts())

1156

In [87]:
data['Cuisines'].value_counts()

Cuisines
North Indian                                                901
North Indian, Chinese                                       474
Fast Food                                                   330
Chinese                                                     323
North Indian, Mughlai                                       313
                                                           ...
North Indian, Chinese, Mediterranean, Asian, Continental      1
Mithai, Beverages                                             1
North Indian, Chinese, Kashmiri                               1
Lucknowi, Mughlai, North Indian                               1
Italian, Continental, American                                1
Name: count, Length: 1156, dtype: int64

In [88]:
data.head(50)

,City,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Price range,Aggregate rating,Votes
865,Faridabad,"Chinese, Fast Food, Bakery",250,0,0,1,2.9,4
866,Faridabad,"North Indian, Chinese",500,0,0,2,2.8,16
867,Faridabad,North Indian,150,0,0,1,2.8,8
868,Faridabad,North Indian,150,0,0,1,2.9,8
869,Faridabad,Bakery,100,0,0,1,2.8,7
870,Faridabad,"Chinese, North Indian, Fast Food",300,0,0,1,3.0,4
871,Faridabad,Mithai,100,0,0,1,0.0,1
872,Faridabad,North Indian,100,0,0,1,0.0,3
873,Faridabad,"North Indian, Mughlai, Chinese",400,0,0,1,0.0,3
874,Faridabad,Cafe,300,0,0,1,0.0,0
875,Faridabad,"Fast Food, North Indian",300,0,0,1,2.9,4
876,Faridabad,"Raw Meats, North Indian, Fast Food",350,0,0,1,3.0,7
877,Faridabad,"Fast Food, Chinese",300,0,0,1,2.9,11
878,Faridabad,North Indian,200,0,0,1,0.0,1
879,Faridabad,"North Indian, Chinese",300,0,0,1,0.0,0
880,Faridabad,North Indian,400,0,0,1,0.0,0
881,Faridabad,"North Indian, Mughlai",600,0,1,2,2.8,49
882,Faridabad,"Fast Food, Burger",500,0,0,2,3.4,58
883,Faridabad,"North Indian, South Indian, Gujarati, Rajasthani",700,0,0,2,3.4,233
884,Faridabad,"Chinese, Thai",1100,0,1,3,3.8,508
885,Faridabad,"Burger, Desserts, Fast Food",600,0,1,2,3.6,98
886,Faridabad,"Cafe, Desserts",900,0,1,2,3.6,59
887,Faridabad,Desserts,300,0,0,1,0.0,0
888,Faridabad,Fast Food,200,0,0,1,0.0,1
889,Faridabad,"American, Fast Food, Salad, Healthy Food",500,0,0,2,0.0,2
890,Faridabad,"American, Fast Food, Burger",500,0,1,2,2.1,57
891,Faridabad,North Indian,1600,0,0,3,4.0,299
892,Faridabad,Chinese,1300,0,1,3,4.1,239
893,Faridabad,"Ice Cream, Desserts",400,0,0,1,3.2,16
894,Faridabad,Fast Food,200,0,1,1,2.7,16
895,Faridabad,"South Indian, North Indian, Chinese",800,0,1,2,3.4,48
896,Faridabad,"North Indian, Mughlai",1000,1,0,3,2.4,25
897,Faridabad,South Indian,200,0,0,1,0.0,3
898,Faridabad,"Desserts, Ice Cream",250,0,0,1,2.8,12
899,Faridabad,Fast Food,200,0,0,1,0.0,2
900,Faridabad,"North Indian, Chinese",1200,1,0,3,0.0,0
901,Faridabad,Cafe,1500,0,0,3,0.0,0
902,Faridabad,"North Indian, Mughlai, Chinese",1500,1,0,3,0.0,0
903,Faridabad,Mithai,100,0,0,1,0.0,2
904,Faridabad,"North Indian, Chinese, Continental",1500,1,0,3,0.0,3
905,Faridabad,North Indian,300,0,0,1,0.0,0
906,Faridabad,"North Indian, Mughlai",500,0,0,2,0.0,0
907,Faridabad,Mughlai,500,0,0,2,0.0,0
908,Faridabad,"North Indian, Chinese",400,0,0,1,0.0,0
909,Faridabad,Bakery,1000,0,0,3,3.0,15
910,Faridabad,Cafe,500,0,0,2,3.2,19
911,Faridabad,"Cafe, Chinese, Fast Food",500,0,0,2,2.8,8
912,Faridabad,"Fast Food, Beverages",300,0,0,1,0.0,0
913,Faridabad,"North Indian, Chinese",450,0,0,1,2.8,20
914,Faridabad,"Fast Food, Chinese, Italian",500,0,0,2,3.1,11

In [89]:
cuisines_f=data.groupby('Cuisines')['Average Cost for two'].mean().sort_values(ascending=False).reset_index()

In [90]:
data.merge(cuisines_f,left_on='Cuisines',right_on='Cuisines')

,City,Cuisines,Average Cost for two_x,Has Table booking,Has Online delivery,Price range,Aggregate rating,Votes,Average Cost for two_y
0,Faridabad,"Chinese, Fast Food, Bakery",250,0,0,1,2.9,4,375.000000
1,Faridabad,"North Indian, Chinese",500,0,0,2,2.8,16,594.303797
2,Faridabad,North Indian,150,0,0,1,2.8,8,399.456160
3,Faridabad,North Indian,150,0,0,1,2.9,8,399.456160
4,Faridabad,Bakery,100,0,0,1,2.8,7,336.084906
...,...,...,...,...,...,...,...,...,...
7917,Noida,"North Indian, Chinese",700,0,1,2,2.6,34,594.303797
7918,Noida,Fast Food,400,0,0,1,0.0,1,277.727273
7919,Noida,Fast Food,600,0,0,2,0.0,3,277.727273
7920,Noida,"North Indian, Chinese",500,0,0,2,0.0,0,594.303797
7921,Noida,"Raw Meats, Fast Food",250,0,0,1,0.0,1,357.954545

In [91]:
data=data.merge(cuisines_f,left_on='Cuisines',right_on='Cuisines')

In [92]:
data.drop(columns=['Cuisines'],inplace=True)

In [93]:
data.head(50)

,City,Average Cost for two_x,Has Table booking,Has Online delivery,Price range,Aggregate rating,Votes,Average Cost for two_y
0,Faridabad,250,0,0,1,2.9,4,375.000000
1,Faridabad,500,0,0,2,2.8,16,594.303797
2,Faridabad,150,0,0,1,2.8,8,399.456160
3,Faridabad,150,0,0,1,2.9,8,399.456160
4,Faridabad,100,0,0,1,2.8,7,336.084906
5,Faridabad,300,0,0,1,3.0,4,310.000000
6,Faridabad,100,0,0,1,0.0,1,152.857143
7,Faridabad,100,0,0,1,0.0,3,399.456160
8,Faridabad,400,0,0,1,0.0,3,717.268041
9,Faridabad,300,0,0,1,0.0,0,605.577689
10,Faridabad,300,0,0,1,2.9,4,326.666667
11,Faridabad,350,0,0,1,3.0,7,351.020408
12,Faridabad,300,0,0,1,2.9,11,333.750000
13,Faridabad,200,0,0,1,0.0,1,399.456160
14,Faridabad,300,0,0,1,0.0,0,594.303797
15,Faridabad,400,0,0,1,0.0,0,399.456160
16,Faridabad,600,0,1,2,2.8,49,751.182109
17,Faridabad,500,0,0,2,3.4,58,477.884615
18,Faridabad,700,0,0,2,3.4,233,700.000000
19,Faridabad,1100,0,1,3,3.8,508,846.808511
20,Faridabad,600,0,1,2,3.6,98,600.000000
21,Faridabad,900,0,1,2,3.6,59,716.666667
22,Faridabad,300,0,0,1,0.0,0,274.468085
23,Faridabad,200,0,0,1,0.0,1,277.727273
24,Faridabad,500,0,0,2,0.0,2,500.000000
25,Faridabad,500,0,1,2,2.1,57,500.000000
26,Faridabad,1600,0,0,3,4.0,299,399.456160
27,Faridabad,1300,0,1,3,4.1,239,547.058824
28,Faridabad,400,0,0,1,3.2,16,345.061728
29,Faridabad,200,0,1,1,2.7,16,277.727273
30,Faridabad,800,0,1,2,3.4,48,631.081081
31,Faridabad,1000,1,0,3,2.4,25,751.182109
32,Faridabad,200,0,0,1,0.0,3,343.689320
33,Faridabad,250,0,0,1,2.8,12,290.476190
34,Faridabad,200,0,0,1,0.0,2,277.727273
35,Faridabad,1200,1,0,3,0.0,0,594.303797
36,Faridabad,1500,0,0,3,0.0,0,605.577689
37,Faridabad,1500,1,0,3,0.0,0,717.268041
38,Faridabad,100,0,0,1,0.0,2,152.857143
39,Faridabad,1500,1,0,3,0.0,3,1058.653846
40,Faridabad,300,0,0,1,0.0,0,399.456160
41,Faridabad,500,0,0,2,0.0,0,751.182109
42,Faridabad,500,0,0,2,0.0,0,383.333333
43,Faridabad,400,0,0,1,0.0,0,594.303797
44,Faridabad,1000,0,0,3,3.0,15,336.084906
45,Faridabad,500,0,0,2,3.2,19,605.577689
46,Faridabad,500,0,0,2,2.8,8,650.000000
47,Faridabad,300,0,0,1,0.0,0,330.681818
48,Faridabad,450,0,0,1,2.8,20,594.303797
49,Faridabad,500,0,0,2,3.1,11,500.000000

In [94]:
data.rename(columns={'Average Cost for two_x':'cost','Average Cost for two_y':'cuisine'},inplace=True)

In [95]:
data.head()

,City,cost,Has Table booking,Has Online delivery,Price range,Aggregate rating,Votes,cuisine
0,Faridabad,250,0,0,1,2.9,4,375.000000
1,Faridabad,500,0,0,2,2.8,16,594.303797
2,Faridabad,150,0,0,1,2.8,8,399.456160
3,Faridabad,150,0,0,1,2.9,8,399.456160
4,Faridabad,100,0,0,1,2.8,7,336.084906

In [96]:
data.corr(numeric_only=True)['cost']

cost                   1.000000
Has Table booking      0.642966
Has Online delivery    0.076953
Price range            0.847985
Aggregate rating       0.328440
Votes                  0.299089
cuisine                0.808274
Name: cost, dtype: float64

In [97]:
y=data.iloc[:,1].values
y.shape

(7922,)

In [98]:
y

array([250, 500, 150, ..., 600, 500, 250])

In [99]:
x=data.drop(columns=['cost']).iloc[:,:].values

In [100]:
x

array([['Faridabad', 0, 0, ..., 2.9, 4, 375.0],
       ['Faridabad', 0, 0, ..., 2.8, 16, 594.3037974683544],
       ['Faridabad', 0, 0, ..., 2.8, 8, 399.4561598224195],
       ...,
       ['Noida', 0, 0, ..., 0.0, 3, 277.72727272727275],
       ['Noida', 0, 0, ..., 0.0, 0, 594.3037974683544],
       ['Noida', 0, 0, ..., 0.0, 1, 357.95454545454544]], dtype=object)

In [101]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
x[:,0]=encoder.fit_transform(x[:,0])

In [102]:
x[:,0]

array([0, 0, 0, ..., 3, 3, 3], dtype=object)

In [103]:
x.shape

(7922, 7)

In [104]:
x[:,0:4]

array([[0, 0, 0, 1],
       [0, 0, 0, 2],
       [0, 0, 0, 1],
       ...,
       [3, 0, 0, 2],
       [3, 0, 0, 2],
       [3, 0, 0, 1]], dtype=object)

In [105]:
x=x[:,1:]

In [106]:
x

array([[0, 0, 1, 2.9, 4, 375.0],
       [0, 0, 2, 2.8, 16, 594.3037974683544],
       [0, 0, 1, 2.8, 8, 399.4561598224195],
       ...,
       [0, 0, 2, 0.0, 3, 277.72727272727275],
       [0, 0, 2, 0.0, 0, 594.3037974683544],
       [0, 0, 1, 0.0, 1, 357.95454545454544]], dtype=object)

In [107]:
from sklearn.model_selection import train_test_split

In [108]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [109]:
from sklearn.linear_model import LinearRegression
regressor1=LinearRegression()

In [110]:
regressor1.fit(x_train,y_train)

LinearRegression()

In [111]:
from sklearn.metrics import r2_score

In [112]:
y_pred=regressor1.predict(x_test)

In [113]:
r2_score(y_test,y_pred)*100

82.47760172225269

In [114]:
y_test

array([ 350, 2500,  200, ...,  300,  100,  100])

In [115]:
y_pred

array([ 230.82847807, 1816.27810821,  247.72632559, ...,  149.62652696,
        301.31809867,  113.0724177 ])

In [116]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 45931.20986122428